from django.db import models

# Create your models here.
EXCHANGES = (
    ('NYSE', 'NYSE (New York Stock Exchange)'),
    ('NASDAQ', 'NASDAQ (NASDAQ Stock Exchange)'),
    ('SSE', 'SSE (Shanghai Stock Exchange)'),
    ('HKEX', 'HKEX (Hong Kong Stock Exchange)'),
    ('SZSE', 'SZSE (Shenzhen Stock Exchange)'),
    ('EURONEXT', 'EURONEXT (Euronext Amsterdam Stock Exchange)'),
    ('LSE', 'LSE (London Stock Exchange)'),
    ('TADAWUL', 'TADAWUL (Saudi Stock Exchange)'),
    ('BSE-BOMBAY', 'BSE-BOMBAY (Bombay Stock Exchange)'),
    ('TSX', 'TSX (Toronto Stock Exchange)'),
    ('NSE-INDIA', 'NSE-INDIA (India National Stock Exchange)'),
    ('FSX', 'FSX (Frankfurt Stock Exchange)'),
    ('SIX', 'SIX (Swiss Stock Exchange)'),
    ('OMX', 'OMX (Stockholm Stock Exchange)'),
    ('KRX', 'KRX (South Korea Stock Exchange)'),
    ('ASX', 'ASX (Australia Stock Exchange)'),
    ('TWSE', 'TWSE (Taiwan Stock Exchange)'),
    ('TSE', 'TSE (Tehran Stock Exchange)'),
    ('JSE', 'JSE (Johannesburg Stock Exchange)'),
    ('BOVESPA', 'BOVESPA (Brazil Stock Exchange)'),
    ('SGX', 'SGX (Singapore Exchange)'),
    ('MOEX', 'MOEX (Moscow Exchange)'),
    ('IDX', 'IDX (Indonesia Stock Exchange)'),
    ('MYX', 'MYX (Malaysia Stock Exchange)'),
    ('BMV', 'BMV (Mexican Stock Exchange)'),
    ('IFB', 'IFB (Iran Fara Bourse)'),
    ('PSE', 'PSE (Philippine Stock Exchange)'),
    ('TASE', 'TASE (Tel-Aviv Stock Exchange)'),
    ('ADX', 'ADX (Abu Dhabi Securities Exchange)'),
    ('BIST', 'BIST (Istanbul Stock Exchange)'),
    ('QE', 'QE (Qatar Stock Exchange)'),
    ('BVS', 'BVS (Santiago Stock Exchange)'),
    ('HOSE', 'HOSE (Ho Chi Minh Stock Exchange)'),
    ('TPEX', 'TPEX (Taipei Exchange)'),
    ('GPW', 'GPW (Warsaw Stock Exchange)'),
    ('NZX', 'NZX (New Zealand Stock Exchange)'),
    ('XKUW', 'XKUW (Kuwait Stock Exchange)'),
    ('BVL', 'BVL (Lima Stock Exchange)'),
    ('DFM', 'DFM (Dubai Financial Market)'),
    ('BVC', 'BVC (Colombia Stock Exchange)'),
    ('BC', 'BC (Casablanca Stock Exchange)'),
    ('NSE-NIGERIA', 'NSE-NIGERIA (Nigerian Stock Exchange)'),
    ('DSE', 'DSE (Dhaka Stock Exchange)'),
    ('EGX', 'EGX (Egyptian Exchange)'),
    ('CSE', 'CSE (Chittagong Stock Exchange)'),
    ('ASE-ATHENS', 'ASE-ATHENS (Athens Stock Exchange)'),
    ('KASE', 'KASE (Kazakhstan Stock Exchange)'),
    ('LUXSE', 'LUXSE (Luxembourg Stock Exchange)'),
    ('BCBA', 'BCBA (Argentinian Stock Exchange)'),
    ('BHB', 'BHB (Bahrain Stock Exchange)'),
    ('BVB', 'BVB (Bucharest Stock Exchange)'),
    ('BSE-BUDAPEST', 'BSE-BUDAPEST (Budapest Stock Exchange)'),
    ('ZSE', 'ZSE (Zagreb Stock Exchagne)'),
    ('NSE-NAIROBI', 'NSE-NAIROBI (Nairobi Securities Exchange)'),
    ('ASE-AMMAN', 'ASE-AMMAN (Amman Stock Exchange)'),
    ('BSE-BULGARIA', 'BSE-BULGARIA (Bulgarian Stock Exchange)'),
    ('MSM', 'MSM (Muscat Securities Market)'),
    ('BVPA', 'BVPA (Panama Stock Exchange)'),
    ('CSE-COLOMBO', 'CSE-COLOMBO (Colombo Stock Exchange)'),
    ('JSE-JAMAICA', 'JSE-JAMAICA (Jamaica Stock Exchange)'),
    ('HNX', 'HNX (Hanoi Stock Exchange)'),
    ('EURONEXT-PARIS', 'EURONEXT-PARIS (Euronext Paris Exchange)'),
    ('BSE-BEIRUT', 'BSE-BEIRUT (Beirut Stock Exchange)'),
    ('SEM', 'SEM (Stock Exchange of Mauritius)'),
    ('MSE', 'MSE (Malta Stock Exchange)'),
    ('UX', 'UX (Ukrainian Exchange)'),
    ('RSE', 'RSE (Rwanda Stock Exchange)'),
    ('PEX', 'PEX (Palestine Securities Exchange)'),
    ('BSE-BOTSWANA', 'BSE-BOTSWANA (Botswana Stock Exchange)'),
    ('BNV', 'BNV (Costa Rican Stock Exchange)'),
    ('NSX', 'NSX (Namibian Stock Exchange)'),
    ('CSX', 'CSX (Cayman Islands Stock Exchange)'),
    ('BSX', 'BSX (Bermuda Stock Exchange)'),
)
class Stock(models.Model):
    ticker = models.CharField(max_length=8, verbose_name="ticker symbol", unique=True)
    name = models.CharField(max_length=255)
    exchange = models.CharField(max_length=128, verbose_name="exchange", unique=False, choices=EXCHANGES)



